export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS"
export const USER_LOGIN_REQUEST_FAILURE = "USER_LOGIN_REQUEST_FAILURE"

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"

export const USER_REGISTER_REQUEST = "USER_LOGIN_REQUEST"
export const USER_REGISTER_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS"
export const USER_REGISTER_REQUEST_FAILURE = "USER_LOGIN_REQUEST_FAILURE"


export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_REQUEST_SUCCESS = "USER_DETAILS_REQUEST_SUCCESS"
export const USER_DETAILS_REQUEST_FAILURE = "USER_DETAILS_REQUEST_FAILURE"
