export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS"
export const USER_LOGIN_REQUEST_FAILURE = "USER_LOGIN_REQUEST_FAILURE"

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST"

export const USER_REGISTER_REQUEST = "USER_LOGIN_REQUEST"
export const USER_REGISTER_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS"
export const USER_REGISTER_REQUEST_FAILURE = "USER_LOGIN_REQUEST_FAILURE"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_REQUEST_SUCCESS = "USER_DETAILS_REQUEST_SUCCESS"
export const USER_DETAILS_REQUEST_FAILURE = "USER_DETAILS_REQUEST_FAILURE"

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_REQUEST_SUCCESS = "USER_UPDATE_PROFILE_REQUEST_SUCCESS"
export const USER_UPDATE_PROFILE_REQUEST_FAILURE = "USER_UPDATE_PROFILE_REQUEST_FAILURE"
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET"
export const USER_UPDATE_PROFILE_SUCCESS_FALSE = "USER_UPDATE_PROFILE_SUCCESS_FALSE"
